export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_COMING_WEATHER = 'GET_COMING_WEATHER';
export const GET_USER_POSITION = 'GET_USER_POSITION';
export const SEARCH_ERROR = 'SEARCH_ERROR';
